#!/usr/bin/env bash

################################################################################
# bootstrap
#
# This script is intended to set up a new Linux desktop machine with my dotfiles
# and other development preferences.
#
# Much of this script was derived from thoughtbot's now unsupported Linux
# version of Laptop.
# https://github.com/thoughtbot/laptop/tree/39768b19959f74724ed0c0ea92e5b2f6f78e45c1
################################################################################


################################################################################
# First, some helpful functions borrowed from Laptop. Thank you, thoughtbot. :)
################################################################################

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}


################################################################################
# Next, a little more setup...
################################################################################

set -e # Terminate script if anything exits with a non-zero value
set -u # Prevent unset variables

osname=$(uname)
divider="====> "
DOTFILES_DIR=$HOME/dotfiles
OLD_DOTFILES_BACKUP=$HOME/old_dotfiles_backup

# Change this if you are using your own fork
DOTFILES_REPO_URL="https://github.com/joshukraine/dotfiles.git"

# Change this value for testing installs of feature branches.
DOTFILES_BRANCH="linux-desktop"


################################################################################
# Make sure we're on Linux before continuing
################################################################################

if [[ "$osname" == 'Darwin' ]]; then
  fancy_echo "Oops, looks like you're on a Mac. Please check out the link
below for instructions on setting up dotfiles on OS X."
  fancy_echo "https://github.com/joshukraine/dotfiles/blob/master/README.md"
  exit 1
elif [[ "$osname" != 'Linux' ]]; then
  fancy_echo "Oops, it looks like you're using a non-supported OS. Exiting..."
  exit 1
fi


################################################################################
# Check for presence of command line tools if OS X
################################################################################

if [ ! -d "$COMMANDLINE_TOOLS" ]; then
  fancy_echo "Apple's command line developer tools must be installed before
running this script. To install them, just run 'gcc' from the terminal and
then follow the prompts. Once the command line tools have been installed,
you can try running this script again."
  exit 1
fi


################################################################################
# 1. Provision with my fork of Laptop
################################################################################

fancy_echo "$divider Step 1: Invoking my fork of thoughtbot's Laptop script..."

curl --remote-name https://raw.githubusercontent.com/joshukraine/laptop/master/mac
sh mac 2>&1 | tee ~/laptop.log


################################################################################
# 2. Install oh-my-zsh
################################################################################

fancy_echo "$divider Step 2: Installing oh-my-zsh..."

if [ -d "$HOME/.oh-my-zsh" ]; then
  rm -rf $HOME/.oh-my-zsh
fi

git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh


################################################################################
# 3. Setup dotfiles
################################################################################

fancy_echo "$divider Step 3: Installing dotfiles..."

if [[ -d $DOTFILES_DIR ]]; then
  fancy_echo "Backing up old dotfiles to $HOME/old_dotfiles_backup..."
  rm -rf $OLD_DOTFILES_BACKUP
  cp -R $DOTFILES_DIR $OLD_DOTFILES_BACKUP
  rm -rf $DOTFILES_DIR
fi

fancy_echo "Cloning your dotfiles repo to ${DOTFILES_DIR} ..."

cd $HOME
git clone $DOTFILES_REPO_URL -b $DOTFILES_BRANCH $DOTFILES_DIR
source "$DOTFILES_DIR/install/symlink_dotfiles"

fancy_echo "Dotfiles setup complete!"


################################################################################
# 4. Install Ukrainian spell-check dictionaries
################################################################################

fancy_echo "$divider Step 4: Installing Ukrainian spell-check dictionaries..."

source "$DOTFILES_DIR/install/install_uk_dictionary"

fancy_echo "Dictionaries installed!"


################################################################################
# 5. Install Powerline-patched fonts
################################################################################

fancy_echo "$divider Step 5: Installing fixed-width fonts patched for use with Powerline symbols..."

if [ -d "$HOME/src/fonts" ]; then
  rm -rf $HOME/src/fonts
fi
git clone https://github.com/powerline/fonts.git $HOME/src/fonts
cd $HOME/src/fonts
./install.sh
cd $HOME
rm -rf $HOME/src/fonts
fancy_echo "Done!"


################################################################################
# 6. Install Vundle and vim plugins
################################################################################

fancy_echo "$divider Step 6: Installing Vundle and vim plugins..."

source "$DOTFILES_DIR/install/vundle"
fancy_echo "Done!"


################################################################################
# 7. Install extra Homebrew packages
################################################################################

fancy_echo "$divider Step 7: Installing extra Homebrew formulae..."

source "$DOTFILES_DIR/install/brew"
fancy_echo "Done!"


################################################################################
# 8. Install Cask and related software
################################################################################

fancy_echo "$divider Step 8: Installing Cask and related software..."

brew_tap 'caskroom/cask'
brew_install_or_upgrade 'brew-cask'
source "$DOTFILES_DIR/install/brew-cask"
fancy_echo "Done!"


################################################################################
# 9. Set OS X preferences
################################################################################

fancy_echo "$divider Step 9: Setting OS X preferences..."

source "$DOTFILES_DIR/osx/defaults"
source "$DOTFILES_DIR/osx/dock"
fancy_echo "OS X prefs set successfully. Some changes may require a restart to take effect."

echo ""
echo "**************************************************************"
echo "**** Setup script complete! Please restart your computer. ****"
echo "**************************************************************"
echo ""
