#!/usr/bin/env bash

################################################################################
# bootstrap
#
# This script is intended to set up a new Linux desktop machine with my dotfiles
# and other development preferences.
#
# Much of this script was derived from thoughtbot's now unsupported Linux
# version of Laptop.
# https://github.com/thoughtbot/laptop/tree/39768b19959f74724ed0c0ea92e5b2f6f78e45c1
################################################################################


# Thank you, thoughtbot! :)
bootstrap_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n[BOOTSTRAP] $fmt\n" "$@"
}


################################################################################
# Variable declarations
################################################################################

osname=$(uname)
ruby_version="2.3.1"
OLD_DOTFILES_BACKUP=$HOME/old_dotfiles_backup

DOTFILES_REPO_URL="https://github.com/joshukraine/linux-dotfiles.git"
DOTFILES_BRANCH="master"
DOTFILES_DIR=$HOME/dotfiles

BOOTSTRAP_REPO_URL="https://github.com/joshukraine/linux-bootstrap.git"
BOOTSTRAP_BRANCH="master"
BOOTSTRAP_DIR=$HOME/linux-bootstrap


################################################################################
# Make sure we're on Linux before continuing
################################################################################

if [[ "$osname" == 'Darwin' ]]; then
  bootstrap_echo "Oops, looks like you're on a Mac. Please check out the link
below for instructions on setting up macOS."
  bootstrap_echo "http://jsua.co/macos"
  exit 1
elif [[ "$osname" != 'Linux' ]]; then
  bootstrap_echo "Oops, it looks like you're using a non-supported OS. Exiting..."
  exit 1
fi


################################################################################
# 1. Update the system.
################################################################################

bootstrap_echo "Step 1: Updating system packages ..."

if command -v aptitude >/dev/null; then
  bootstrap_echo "Using aptitude ..."
else
  bootstrap_echo "Installing aptitude ..."
  sudo apt-get install -y aptitude
fi

sudo aptitude update


################################################################################
# 2. Install basic tools
################################################################################

bootstrap_echo "Step 2: Installing basic tools..."

bootstrap_echo "Installing curl ..."
sudo aptitude install -y curl

bootstrap_echo "Installing git..."
sudo aptitude install -y git

bootstrap_echo "Installing python software properties..."
sudo aptitude install -y python-software-properties

bootstrap_echo "Installing build-essential..."
sudo aptitude install -y build-essential

# https://gorails.com/setup/ubuntu/14.04
bootstrap_echo "Installing libraries for common Ruby/Rails/gem dependencies..."
sudo aptitude install -y zlib1g-dev libssl-dev libreadline-dev libyaml-dev libsqlite3-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev

bootstrap_echo "Installing sqlite3..."
sudo aptitude install -y sqlite3

bootstrap_echo "Installing Postgres..."
sudo aptitude install -y postgresql postgresql-server-dev-all

bootstrap_echo "Installing Redis..."
sudo aptitude install -y redis-server

bootstrap_echo "Installing ctags..."
sudo aptitude install -y exuberant-ctags

bootstrap_echo "Installing Vim ..."
sudo aptitude remove vim-tiny -y
sudo aptitude install -y vim-gtk

bootstrap_echo "Installing htop..."
sudo aptitude install -y htop

bootstrap_echo "Installing tree..."
sudo aptitude install -y tree

if grep -qiE 'precise|saucy|trusty|utopic|vivid' /etc/os-release; then
  bootstrap_echo "Adding tmux ppa:pi-rho/dev..."
  sudo add-apt-repository -y ppa:pi-rho/dev
  sudo aptitude update
fi

bootstrap_echo "Installing tmux..." # http://stackoverflow.com/a/25952511
if grep -qiE 'trusty' /etc/os-release; then
  sudo aptitude install -y tmux=2.0-1~ppa1~t
elif grep -qiE 'vivid' /etc/os-release; then
  sudo aptitude install -y tmux=2.0-1~ppa1~v
else
  sudo aptitude install -y tmux
fi

bootstrap_echo "Installing ImageMagick..."
sudo aptitude install -y imagemagick

bootstrap_echo "Installing zsh..."
sudo aptitude install -y zsh

bootstrap_echo "Installing xclip..."
sudo aptitude install -y xclip

if grep -qiE 'precise|saucy|trusty|utopic|vivid|wheezy' /etc/os-release; then
  bootstrap_echo "Installing gnome-tweak-tool..."
  sudo aptitude install -y gnome-tweak-tool
fi

bootstrap_echo "Installing node via NVM..."
export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"

nvm install 5

bootstrap_echo "Cloning linux-bootstrap repo..."
git clone $BOOTSTRAP_REPO_URL -b $BOOTSTRAP_BRANCH $BOOTSTRAP_DIR


################################################################################
# 3. Install oh-my-zsh
################################################################################

bootstrap_echo "Step 3: Installing oh-my-zsh..."

if [ -d "$HOME/.oh-my-zsh" ]; then
  rm -rf $HOME/.oh-my-zsh
fi

git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

bootstrap_echo "Changing your shell to zsh ..."
chsh -s $(which zsh)


################################################################################
# 4. Setup dotfiles
################################################################################

bootstrap_echo "Step 4: Installing dotfiles..."
if [[ -d $DOTFILES_DIR ]]; then
  bootstrap_echo "Backing up old dotfiles to $HOME/old_dotfiles_backup..."
  rm -rf $OLD_DOTFILES_BACKUP
  cp -R $DOTFILES_DIR $OLD_DOTFILES_BACKUP
  rm -rf $DOTFILES_DIR
fi

bootstrap_echo "Cloning your dotfiles repo to ${DOTFILES_DIR} ..."

git clone $DOTFILES_REPO_URL -b $DOTFILES_BRANCH $DOTFILES_DIR
source $DOTFILES_DIR/install.sh


################################################################################
# 5. Install ~/bin utilities
################################################################################

bootstrap_echo "Step 5: Installing bin utilities..."

if [ ! -d "$HOME/bin" ]; then
  mkdir $HOME/bin
fi

cp -R $BOOTSTRAP_DIR/bin/* $HOME/bin/


################################################################################
# 6. Install Powerline-patched fonts
################################################################################

bootstrap_echo "Step 6: Installing fixed-width fonts patched for use with Powerline symbols..."
if [ -d "$HOME/src/fonts" ]; then
  rm -rf $HOME/src/fonts
fi
git clone https://github.com/powerline/fonts.git $HOME/src/fonts
cd $HOME/src/fonts
./install.sh
cd $HOME
rm -rf $HOME/src/fonts

bootstrap_echo "Done!"


################################################################################
# 7. Install Vundle and Vim plugins
################################################################################

bootstrap_echo "Step 7: Installing Vundle and Vim plugins..."
if [ -d $HOME/.vim/bundle ]; then
  rm -rf $HOME/.vim/bundle
fi
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
cp -R $DOTFILES_DIR/vim/colors $HOME/.vim # So Vim won't complain about solarized not being found.
vim +PluginInstall +qall
rm -rf $HOME/.vim/colors

bootstrap_echo "Done!"


################################################################################
# 8. Install rbenv and ruby-build
################################################################################

bootstrap_echo "Step 8: Installing rbenv and ruby-build..."
if [[ ! -d "$HOME/.rbenv" ]]; then
  bootstrap_echo "Installing rbenv..."
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init - zsh)"
fi

if [[ ! -d "$HOME/.rbenv/plugins/ruby-build" ]]; then
  bootstrap_echo "Installing ruby-build..."
  git clone https://github.com/sstephenson/ruby-build.git \
    ~/.rbenv/plugins/ruby-build
fi

bootstrap_echo "Done!"


################################################################################
# 9. Install Ruby, Rails, and friends
################################################################################

bootstrap_echo "Step 9: Installing Ruby, Rails, and friends..."

bootstrap_echo "Installing Ruby $ruby_version ..."
rbenv install -s "$ruby_version"

bootstrap_echo "Setting $ruby_version as global default Ruby ..."
rbenv global "$ruby_version"

bootstrap_echo "Updating to latest Rubygems version ..."
gem update --system

bootstrap_echo "Installing Bundler..."
gem install bundler --no-document --pre

bootstrap_echo "Installing Rails..."
gem install rails

bootstrap_echo "Done!"


################################################################################
# 10. Set up Tmuxinator (https://github.com/tmuxinator/tmuxinator)
################################################################################

bootstrap_echo "Step 10: Setting up Tmuxinator..."

gem install tmuxinator

if [ ! -d "$HOME/.tmuxinator/" ]; then
  mkdir "$HOME/.tmuxinator"
fi

cp $BOOTSTRAP_DIR/lib/default.yml $HOME/.tmuxinator/

bootstrap_echo "Done!"

echo ""
echo "******************************************************************"
echo "**** Bootstrap script complete! Please restart your computer. ****"
echo "******************************************************************"
echo ""
